branches:
  only:
  - master
  - "/^v0.*$/"
language: python
python:
- '3.5'
cache: pip
install:
- pip install --upgrade pip
- pip install --upgrade -r requirements.txt
script:
- pupa update --scrape lametro bills window=30 --fastmode
after_success:
- export SENTRY_ORG=datamade
- VERSION=$(sentry-cli releases propose-version)
- sentry-cli releases new -p ocd-scrapers $VERSION
- sentry-cli releases set-commits --auto $VERSION
deploy:
  provider: codedeploy
  access_key_id: AKIAJNYGDLOJKHOUWCAA
  secret_access_key:
    secure: CpDzdMiluV31OF3DHshmSgQ0w3oMOP3Zyi/rLqJYqUbYhcP9tWMBHUo0VwjUUjtdt0PSAbP68rLFuLLKR4qAled6xA4Zdj/idtBBpykmu/rGQAJCxeEcjQyzuN59r1eX4BbbRk8Zw7Ts0ZNLKxEFyQg9L8KoPtwH3OuwJKc24zs4+nzjFFAM3len9u6lOtixZ0gtzY/TUOj7mAoqXIvPpB2x5tu9DfENF6HTbb85yZ4KlVFCMVKTyK5NooI+HWlxXsRS4srTT9icc/M1wrJC7BhJxZLkGEiQpdC2nga78dp/2SGJ0cFZUgZs/o97h5ILLEVDmXdQy0BHkuI6qr562y5sPngcis7y68eDB65UnxlFC/QhYii+hXRpLDse4LudSKZ+UHrtTH56aIBHrkVfj68BPkmnOWGy+tHuQPhpDsbFjtSvtwOWJNL/y+qosJj89ZrvDoEWneaFcwVbBvZuyURQ2KDXipZ2yQbGcL5cizebf2OdQke2fxRQMTROra3JA9BrxGEFQvDd0cT4wIBtbuELq5iQBoqj/ajwf0LfFrQhFLf6cFjKXR6BLEZJG8+oQJmuYfOoSMFxe0hvUjUperwejan8MmyNaXkDSFgv+5uVcD88Q4RNOiRKmlv+CpaSiv7IChwekTuSmzQdMa8AGAFuiAkZOctpx/JLL197w1o=
  revision_type: github
  application: scrapers-us-municipal
  deployment_group: production
  on:
    tags: true
